#custom
overrides:
  ansible.cephlab:
    branch: containerized-nodes
    skip_tags: "timezone,nagios,monitoring-scripts,ssh,hostname,pubkeys,zap,sudoers,kerberos,selinux,lvm,ntp-client,resolvconf,packages,cpan"
    vars:
      containerized_node: true
      ansible_user: root
      cm_user: root
      start_rpcbind: false
  cephadm:
    image: docker.io/ceph/ceph:v15.2.9
    cephadm_branch: v15.2.9
    cephadm_git_url: https://github.com/ceph/ceph